Feature: REGIONAL Record Customer Contact
  Records posted will depend on the parameters set on the PUT request.

  Scenario Outline: Record Customer Contact - <entity>_<sourceSystem>_<lob>_<TCNo> - Successful update of records

    Given the following http headers are set Record Customer Contact
      | X-Axa-Entity | X-Axa-MsgId | X-Axa-InitialMsgId | X-Axa-Env | X-Axa-ContextHeader-CustomData-TargetSystem | X-Axa-ContextHeader-CustomData-SourceSystem | X-Axa-RequestingChannel   | Accept   | x-axa-CallbackFlag |
      | <entity>     | <msgId>     | <initialMsgId>     | <env>     | <targetSystem>                              | <sourceSystem>                              | <x-axa-requestingchannel> | <accept> | <CallbackFlag>     |

    And the following PAYLOAD request body is set for Record Customer Contact
      | payload   | coreDBPartyId   | partyId   | masterIndividualId   | telephoneNumber   | telephoneAddressTypeCode   | primaryFlag   | physicalAddressTypeCode   | addressLine1   | addressLine2   | addressLine3   | addressLine4   | addressLine5   | countryCode   | postalCode   | primaryAddressFlag   | electronicAddressTypeCode   | electronicAddress   | idTYpe   | idValue   |
      | <payload> | <coreDBPartyId> | <partyId> | <masterIndividualId> | <telephoneNumber> | <telephoneAddressTypeCode> | <primaryFlag> | <physicalAddressTypeCode> | <addressLine1> | <addressLine2> | <addressLine3> | <addressLine4> | <addressLine5> | <countryCode> | <postalCode> | <primaryAddressFlag> | <electronicAddressTypeCode> | <electronicAddress> | <idTYpe> | <idValue> |

    When the api call has been made for Record Customer Contact

    Then verify that API response matches for Record Customer Contact
      | sourceMsgID | contextID | status   |
      | <msgId>     | <msgId>   | <status> |

    Then verify that records are updated in DB for Record Customer Contact

  @SG
    Examples:
      | TCNo | entity | lob    | msgId      | initialMsgId | env  | targetSystem | sourceSystem | x-axa-requestingchannel | accept           | CallbackFlag | payload                           | status    | coreDBPartyId   | partyId | masterIndividualId | telephoneNumber | telephoneAddressTypeCode | primaryFlag | physicalAddressTypeCode | addressLine1                  | addressLine2                   | addressLine3          | addressLine4 | addressLine5 | countryCode | postalCode | primaryAddressFlag | electronicAddressTypeCode | electronicAddress     | idTYpe | idValue  |
      | 0001 | SG     | Life   | [$autogen] | [$autogen]   | PPE1 | COREDB       | SCRM         | SFDC                    | application/json | Y            | recordCustomerContact_SG_0001.txt | Submitted | 920000001971948 | 2019723 |                    | 1122334455      | FAX                      | Y           | RES                     | New Chu Kang Crescent         | Singapore                      | New                   | Khua         | Rhua         | SIN         | 6836901    | Y                  | EML                       | new2649141@gmail1.com | Policy | P1961266 |
      | 0002 | SG     | Life   | [$autogen] | [$autogen]   | PPE1 | COREDB       | MYAXA        | SFDC                    | application/json | Y            | recordCustomerContact_SG_0001.txt | Submitted | 920000001971949 | 2019724 |                    | 1122334455      | FAX                      | Y           | RES                     | New Chu Kang Crescent         | Singapore                      | New                   | Khua         | Rhua         | SIN         | 6836901    | Y                  | EML                       | new2649141@gmail1.com | Policy | P1961266 |
      | 0003 | SG     | Life   | [$autogen] | [$autogen]   | PPE1 | COREDB       | IAAS         | SFDC                    | application/json | Y            | recordCustomerContact_SG_0001.txt | Submitted | 920000001971950 | 2019725 |                    | 1122334455      | FAX                      | Y           | RES                     | New Chu Kang Crescent         | Singapore                      | New                   | Khua         | Rhua         | SIN         | 6836901    | Y                  | EML                       | new2649141@gmail1.com | Policy | P1961266 |
      | 0004 | SG     | GI     | [$autogen] | [$autogen]   | PPE1 | COREDB       | SCRM         | SFDC                    | application/json | Y            | recordCustomerContact_SG_0001.txt | Submitted | 920000000000156 | 0000159 |                    | 1122334455      | FAX                      | Y           | BCOR                    | 038 DQEHITKLGF KGQR           | #85-89 HOFTL WXOSROFU          |                       |              |              | SIN         | 348574     | Y                  | EML                       | new2649141@gmail1.com | Policy | 40100964 |
      | 0005 | SG     | GI     | [$autogen] | [$autogen]   | PPE1 | COREDB       | MYAXA        | SFDC                    | application/json | Y            | recordCustomerContact_SG_0001.txt | Submitted | 920000000000158 | 0000161 |                    | 1122334455      | FAX                      | Y           | BCOR                    | Q/E ZTKDOFQZTR VTY 29/90/0887 | WSA 094 ZGQ HQNGI SGK 5#83-729 |                       |              |              | SIN         | 310219     | Y                  | EML                       | new2649141@gmail1.com | Policy | 40100968 |
      | 0006 | SG     | GI     | [$autogen] | [$autogen]   | PPE1 | COREDB       | IAAS         | SFDC                    | application/json | Y            | recordCustomerContact_SG_0001.txt | Submitted | 920000000000160 | 0000163 |                    | 1122334455      | FAX                      | Y           | BCOR                    | 38 EIQFUO LGXZI LZKTTZ 9      | WSA 055-U #93-038              | WXAOZ WQZGA LZKTTZ 01 |              |              | SIN         | 486764     | Y                  | EML                       | new2649141@gmail1.com | Policy | 40100772 |
      | 0007 | SG     | Health | [$autogen] | [$autogen]   | PPE1 | COREDB       | SCRM         | SFDC                    | application/json | Y            | recordCustomerContact_SG_0001.txt | Submitted | 920000001909599 | 1955851 |                    | 1122334455      | FAX                      | Y           | RES                     |                               |                                |                       |              |              | SIN         | 068898     | Y                  | EML                       | new2649141@gmail1.com | Policy | 60099649 |
      | 0008 | SG     | Health | [$autogen] | [$autogen]   | PPE1 | COREDB       | MYAXA        | SFDC                    | application/json | Y            | recordCustomerContact_SG_0001.txt | Submitted | 920000002044383 | 6000398 |                    | 1122334455      | FAX                      | Y           | RES                     | test                          | address                        | not                   | valid        |              | SIN         | 570402     | Y                  | EML                       | new2649141@gmail1.com | Policy | 60099809 |
      | 0009 | SG     | Health | [$autogen] | [$autogen]   | PPE1 | COREDB       | IAAS         | SFDC                    | application/json | Y            | recordCustomerContact_SG_0001.txt | Submitted | 920000002046699 | 6002852 |                    | 1122334455      | FAX                      | Y           | RES                     | 2 OFZTKFQZOGFQS WXLOFTLL HQKA | #81-06 FGKROE TXKGHTQF ETFZKT  |                       |              |              | SIN         | 609927     | Y                  | EML                       | new2649141@gmail1.com | Policy | 60099845 |

  @HK
    Examples:
      | TCNo | entity | lob  | msgId      | initialMsgId | env  | targetSystem | sourceSystem | x-axa-requestingchannel | accept           | CallbackFlag | payload                           | status    | coreDBPartyId   | partyId | masterIndividualId | telephoneNumber | telephoneAddressTypeCode | primaryFlag | physicalAddressTypeCode | addressLine1                  | addressLine2     | addressLine3                | addressLine4     | addressLine5 | countryCode | postalCode | primaryAddressFlag | electronicAddressTypeCode | electronicAddress   | idTYpe | idValue  |
      | 0001 | HK     | PSEA | [$autogen] | [$autogen]   | PPE1 | COREDB       | SCRM         | SFDC                    | application/json | Y            | recordCustomerContact_HK_0001.txt | Submitted | 230000000049191 | 0034880 |                    | 1122334455      | FAX                      | Y           | RES                     | E/G KGZQKN OFYGKDQZOGF ETFZKT | 93/Y             | EQHOZQS EGDDTKEOQS WXOSROFU | 07 STOUIZGF KGQR | EQXLTVQN WQN | HK          |            | Y                  | EML                       |                     | Policy | 53638793 |
      | 0002 | HK     | PSEA | [$autogen] | [$autogen]   | PPE1 | COREDB       | SCRM         | SFDC                    | application/json | Y            | recordCustomerContact_HK_0002.txt | Submitted | 230000000268888 | 0264850 |                    | 1122334455      | FAX                      | Y           | RES                     | KGGD 685                      | LOFETKT WXOSROFU | 37 YGKWTL LZKTTZ            | VTLZ HGOFZ       |              | HK          |            | Y                  | EML                       | LNTXFU@USOFA.FTZ.IA | Policy | 53638793 |